### ISSUE TITLE
It doesn't say any error when nodejs engine path is invalid

### ISSUE THREAD

**Issue by GregYeo** [jimkyndemeyer/js-graphql-intellij-plugin#100]
It happens for very few people but i was about to give up for it.
I may not need to solve but i hope if someone is having trouble, please check below.

# Bug
GraphQL Plugin Service just stuck with red line.
I tried to restart GraphQL plugin service several times but it was same result.
<img width="970" alt="screen shot 2017-09-18 at 7 37 36 am" src="https://user-images.githubusercontent.com/15027781/30525580-4f49b8e4-9c44-11e7-9b51-590b06dabef7.png">
The red line description has nothing.

And GraphQL type color and type tracing are not working even if config has GraphQL scheme file
<img width="783" alt="screen shot 2017-09-18 at 7 37 44 am" src="https://user-images.githubusercontent.com/15027781/30525579-4f4970e6-9c44-11e7-8a79-d4861b28c3a4.png">

# Cause
<img width="830" alt="screen shot 2017-09-18 at 7 29 25 am" src="https://user-images.githubusercontent.com/15027781/30525544-64d6d008-9c43-11e7-98ef-9c10fd78216d.png">

I could use this plugin in native app project using nodejs. But It has happened only back end server project (java, kotlin, scala) because i did not need to specify what the nodejs is.

IDE fatal error says 
```
Error running JS GraphQL Language Service using Node.js: Cannot run program "/Users/greg/.nvm/versions/node/v8.0.0/bin/node" (in directory "/Users/greg/Library/Application Support/IntelliJIdea2017.2"): error=2, No such file or directory

Error running JS GraphQL Language Service using Node.js: Cannot run program "/Users/greg/.nvm/versions/node/v8.0.0/bin/node" (in directory "/Users/greg/Library/Application Support/IntelliJIdea2017.2"): error=2, No such file or directory
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/Users/greg/.nvm/versions/node/v8.0.0/bin/node" (in directory "/Users/greg/Library/Application Support/IntelliJIdea2017.2"): error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:391)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceInstance.createProcessHandler(JSGraphQLNodeLanguageServiceInstance.java:135)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceInstance.<init>(JSGraphQLNodeLanguageServiceInstance.java:83)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.getJSGraphQLNodeLanguageServiceInstance(JSGraphQLNodeLanguageServiceClient.java:118)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.executeRequest(JSGraphQLNodeLanguageServiceClient.java:71)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.executeRequest(JSGraphQLNodeLanguageServiceClient.java:66)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.getTokens(JSGraphQLNodeLanguageServiceClient.java:33)
	at com.intellij.lang.jsgraphql.lexer.JSGraphQLLexer.fetchTokensFromLanguageService(JSGraphQLLexer.java:78)
	at com.intellij.lang.jsgraphql.lexer.JSGraphQLLexer.start(JSGraphQLLexer.java:66)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.a(LexerEditorHighlighter.java:378)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:359)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.loadEditorInBackground(TextEditorImpl.java:70)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:50)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.a(AsyncEditorLoader.java:100)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$2(PsiDocumentManagerBase.java:502)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:953)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:500)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.a(AsyncEditorLoader.java:98)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.a(AsyncEditorLoader.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "/Users/greg/.nvm/versions/node/v8.0.0/bin/node" (in directory "/Users/greg/Library/Application Support/IntelliJIdea2017.2"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:420)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:387)
	... 32 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
```

It could be IDE  but i did not recognized the IDE fatal error until i am writing this issue. because it doesn't pop up.
I think the plugin can show initializing error. That's the solution i wanted.
Nothing message makes the plugin having problem but not user.

# Solution
You should change Nodejs engine path as valid.
Then, you `MUST RESTART INTELLIJ IDE COMPLETELY` to reload nodejs engine.
That's it.

**Comment by jimkyndemeyer** [comment]
Hi GregYeo.

Thanks for using the plugin.

The upcoming 1.6 release will show a notification when the Node.js process fails to start.

**Comment by jimkyndemeyer** [comment]
Version 1.6 has been uploaded to the plugin repository and is now pending approval by Jetbrains.
