### ISSUE TITLE
version 1.6.1 crashes in PyCharm 2017.2.3

### ISSUE THREAD

**Issue by stebunovd** [jimkyndemeyer/js-graphql-intellij-plugin#107]
This happens after upgrade from 1.6.0 to 1.6.1. There were no other changes in my setup, and v1.6.0 didn't cause such error:

```
/usr/local/bin/node "/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js" --port=60718
JS GraphQL listening on http://127.0.0.1:60718/js-graphql-language-service
Setting Project Dir '/Users/dvs/Dropbox/Code/jirobot'
Watching '/Users/dvs/Dropbox/Code/jirobot/graphql.config.json' for changes.
Watching '/Users/dvs/Dropbox/Code/jirobot/code/frontend/graphql.schema.json' for changes.
Loaded schema from '/Users/dvs/Dropbox/Code/jirobot/code/frontend/graphql.schema.json': {"data":{"__schema":{"queryType":{"name":"Query"},"mutationType":null,"subscriptionType":null,"types":[{"kind":"OBJECT","name":"Query","description":null,"fields":[{"name":"viewer","description":null,"args":[],"type":{"kind":"OBJECT","name":"Viewer","ofType":null},"isDeprecated":false,"deprecationReason":null}],"inputFields":null,"interfaces":[],"enumValues":null,"possibleTypes":null},{"kind":"OBJECT","name":"Viewer","description":null,"fields":[{"name":"id","description":"The ID of the object." ...
TypeError: Cannot read property '0' of undefined
    at /Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:16161:35
    at getAnnotations (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:161924:27)
    at /Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:161617:24
    at Layer.handle [as handle_request] (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30617:5)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30831:13)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30825:14)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30825:14)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30825:14)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30825:14)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30825:14)
TypeError: Cannot read property '0' of undefined
    at /Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:16161:35
    at getAnnotations (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:161924:27)
    at /Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:161617:24
    at Layer.handle [as handle_request] (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30617:5)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30831:13)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30825:14)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30825:14)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30825:14)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30825:14)
    at next (/Users/dvs/Library/Application Support/PyCharm2017.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js:30825:14)
```

**Comment by stebunovd** [comment]
UPD: The problem persists in PyCharm 2017.3

**Comment by jimkyndemeyer** [comment]
Hi Dennis.

This issue appears to be dependent on the specific GraphQL that is validated by the language service.

Can you keep an eye on the GraphQL console and figure out which GraphQL text buffer that triggers it? You can trigger the validation simply by adding and remove the '#' GraphQL comment character.

If you can, I'd like you to add the GraphQL text as a comment on this issue to help reproduce and fix. It would also help if you can attach your graphql.schema.json, or a relevant subset with the types being selected by the GraphQL in question.

Thanks,
Jim.

**Comment by stebunovd** [comment]
Hi Jim,

please see https://gist.github.com/stebunovd/96f989c15cef7238b7da0da6ec372e70


thanks,

Denis

**Comment by jimkyndemeyer** [comment]
Hi Denis.

Please give the 2.0 beta-1 release a go. Instructions at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-1

Let me know if there's any issues.

Best regards,
Jim.
