### ISSUE TITLE
Error with https

### ISSUE THREAD

**Issue by maarekj** [jimkyndemeyer/js-graphql-intellij-plugin#113]
My schema is on my local https server.
The server certificate is self-signed.
Problem: This plugin does not support self-signed certificates.

*graphql.config.json:*
```json
{
  "schema": {
    "request": {
      "url" : "https://www.localserver.com/graphql",
      "method" : "POST",
      "postIntrospectionQuery" : true,
      "options" : {
        "headers": {
          "user-agent" : "JS GraphQL"
        }
      }
    }
  },
  "endpoints" : [
    {
      "name": "Default (https://www.localserver.com/graphql)",
      "url": "https://www.localserver.com/graphql",
      "options" : {
        "headers": {
          "user-agent" : "JS GraphQL"
        }
      }
    }
  ]
}
```

*GraphQl Console:*
```
JS GraphQL listening on http://127.0.0.1:64608/js-graphql-language-service
Setting Project Dir '/Applications/MAMP/htdocs/netosoft/goafrica'
Watching '/Applications/MAMP/htdocs/netosoft/goafrica/graphql.config.json' for changes.
Error loading schema from 'https://www.localserver.com/graphql' { Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1104:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:468:38) code: 'CERT_HAS_EXPIRED' } { url: 'https://www.localserver.com/graphql',
  method: 'POST',
  README_postIntrospectionQuery: 'Whether to POST an introspectionQuery to the url. If the url always returns the schema JSON, set to false and consider using GET',
  postIntrospectionQuery: true,
  README_options: 'See the \'Options\' section at https://github.com/then/then-request',
  options: 
   { headers: 
      { 'user-agent': 'JS GraphQL',
        'Content-Type': 'application/json',
        'Content-Length': 1550,
        'Accept-Encoding': 'gzip,deflate' },
     body: '{"query":"\\n  query IntrospectionQuery {\\n    __schema {\\n      queryType { name }\\n      mutationType { name }\\n      subscriptionType { name }\\n      types {\\n        ...FullType\\n      }\\n      directives {\\n        name\\n        description\\n        locations\\n        args {\\n          ...InputValue\\n        }\\n      }\\n    }\\n  }\\n\\n  fragment FullType on __Type {\\n    kind\\n    name\\n    description\\n    fields(includeDeprecated: true) {\\n      name\\n      description\\n      args {\\n        ...InputValue\\n      }\\n      type {\\n        ...TypeRef\\n      }\\n      isDeprecated\\n      deprecationReason\\n    }\\n    inputFields {\\n      ...InputValue\\n    }\\n    interfaces {\\n      ...TypeRef\\n    }\\n    enumValues(includeDeprecated: true) {\\n      name\\n      description\\n      isDeprecated\\n      deprecationReason\\n    }\\n    possibleTypes {\\n      ...TypeRef\\n    }\\n  }\\n\\n  fragment InputValue on __InputValue {\\n    name\\n    description\\n    type { ...TypeRef }\\n    defaultValue\\n  }\\n\\n  fragment TypeRef on __Type {\\n    kind\\n    name\\n    ofType {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n          ofType {\\n            kind\\n            name\\n            ofType {\\n              kind\\n              name\\n              ofType {\\n                kind\\n                name\\n                ofType {\\n                  kind\\n                  name\\n                }\\n              }\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n"}' } }
```

**Comment by jimkyndemeyer** [comment]
Hi maarekj.

The language service itself relies on `then-request` to do the introspection. It doesn't seem to have any options to skip the check.

Working with self-signed certificates seem rather complicated: https://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired

My recommendation is that you don't use the request option in combination with HTTPS, but rather rely on one of two alternatives:
- The file options with a schema.json where you generated the file by handling the introspection request your self
- The file options using a .graphqls that describes the schema

**Comment by maarekj** [comment]
Thank you for your detailed answer
