### ISSUE TITLE
ClassCastException in IntelliJ IDEA 2018.1 EAP

### ISSUE THREAD

**Issue by szhhe** [jimkyndemeyer/js-graphql-intellij-plugin#135]
JS GraphQL Plugin 1.7 + IDEA 2018

IntelliJ IDEA 2018.1 EAP (Ultimate Edition)
Build #IU-181.4203.6, built on March 13, 2018
IntelliJ IDEA EAP User
Expiration date: April 12, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

com.intellij.psi.impl.source.PsiPlainTextFileImpl cannot be cast to com.intellij.lang.jsgraphql.schema.psi.JSGraphQLSchemaFile
java.lang.ClassCastException: com.intellij.psi.impl.source.PsiPlainTextFileImpl cannot be cast to com.intellij.lang.jsgraphql.schema.psi.JSGraphQLSchemaFile
	at com.intellij.lang.jsgraphql.schema.ide.project.JSGraphQLSchemaLanguageProjectService.getOrCreateSchemaFileElements(JSGraphQLSchemaLanguageProjectService.java:630)
	at com.intellij.lang.jsgraphql.schema.ide.project.JSGraphQLSchemaLanguageProjectService.lambda$onProcessHandlerTextAvailable$0(JSGraphQLSchemaLanguageProjectService.java:387)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by slorber** [comment]
+1 it seems the plugin fails to load on newest IDEA

**Comment by jimkyndemeyer** [comment]
Hi Sebastien.

Can you take a look at #148 and see if that's your issue?

**Comment by slorber** [comment]
thanks it seems to be the issue

**Comment by jimkyndemeyer** [comment]
Appears to be related to the file size as reported in #163.  Closing in favor of that issue since it's reported for a non-EAP version.
