### ISSUE TITLE
IntelliJ 2018.2 touchbar-related exception

### ISSUE THREAD

**Issue by blackxored** [jimkyndemeyer/js-graphql-intellij-plugin#169]
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'actions' of com/intellij/ui/mac/touchbar/TouchBar.buildFromGroup must not be null
	at com.intellij.ui.mac.touchbar.TouchBar.$$$reportNull$$$0(TouchBar.java)
	at com.intellij.ui.mac.touchbar.TouchBar.buildFromGroup(TouchBar.java)
	at com.intellij.ui.mac.touchbar.TouchBarsManager.onUpdateEditorHeader(TouchBarsManager.java:300)
	at com.intellij.openapi.editor.impl.EditorImpl.setHeaderComponent(EditorImpl.java:1817)
	at com.intellij.lang.jsgraphql.ide.project.JSGraphQLLanguageUIProjectService.createToolWindowResultEditor(JSGraphQLLanguageUIProjectService.java:675)
	at com.intellij.lang.jsgraphql.ide.project.JSGraphQLLanguageUIProjectService.lambda$null$12(JSGraphQLLanguageUIProjectService.java:712)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at com.intellij.cloudConfig.CloudConfigManager.waitDone(CloudConfigManager.java:1368)
	at com.intellij.cloudConfig.CloudConfigManager.getRepositoryPlugins(CloudConfigManager.java:1352)
	at com.intellij.cloudConfig.CloudConfigManager.getInstalledPlugins(CloudConfigManager.java:1327)
	at com.intellij.cloudConfig.CloudConfigManager.updatePlugins(CloudConfigManager.java:1423)
	at com.intellij.cloudConfig.CloudConfigManager.safeUpdatePlugins(CloudConfigManager.java:1377)
	at com.intellij.cloudConfig.CloudConfigManager.lambda$doConnection$11(CloudConfigManager.java:614)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jimkyndemeyer** [comment]
Duplicates #166
