### ISSUE TITLE
Introspection request returning 400 possibly because of newlines?

### ISSUE THREAD

**Issue by dank** [jimkyndemeyer/js-graphql-intellij-plugin#176]
## Version and Environment Details
__Operation system__: 
macOS El Capitan
__IDE name and version__: 
WebStorm 2017.3.2
__Plugin version__: 
1.7.2

## Expected Behaviour
Return introspection data correctly

## Actual Behaviour

```/Users/dan/.nvm/versions/node/v10.8.0/bin/node --no-deprecation "/Users/dan/Library/Application Support/WebStorm2017.3/js-graphql-intellij-plugin/js-graphql-language-service.dist.js" --port=63474
JS GraphQL listening on http://127.0.0.1:63474/js-graphql-language-service
Setting Project Dir '/Users/dan/Projects/proxy'
Watching '/Users/dan/Projects/proxy/graphql.config.json' for changes.
Error loading schema from 'http://localhost:8080/api/graphql' Response {
  statusCode: 400,
  headers:
   { 'x-powered-by': 'Express',
     'access-control-allow-origin': '*',
     vary: 'Origin',
     'access-control-allow-credentials': 'true',
     'content-type': 'application/json',
     date: 'Fri, 31 Aug 2018 23:26:31 GMT',
     connection: 'close',
     'transfer-encoding': 'chunked' },
  body:
   <Buffer 7b 22 65 72 72 6f 72 73 22 3a 5b 7b 22 6d 65 73 73 61 67 65 22 3a 22 43 6f 6e 74 65 78 74 20 63 72 65 61 74 69 6f 6e 20 66 61 69 6c 65 64 3a 20 49 6e ... >,
  url: undefined } { url: 'http://localhost:8080/api/graphql',
  method: 'POST',
  postIntrospectionQuery: true,
  options:
   { headers:
      { 'Content-Type': 'application/json',
        'Content-Length': 1550,
        'Accept-Encoding': 'gzip,deflate' },
     body:
      '{"query":"\\n  query IntrospectionQuery {\\n    __schema {\\n      queryType { name }\\n      mutationType { name }\\n      subscriptionType { name }\\n      types {\\n        ...FullType\\n      }\\n      directives {\\n        name\\n        description\\n        locations\\n        args {\\n          ...InputValue\\n        }\\n      }\\n    }\\n  }\\n\\n  fragment FullType on __Type {\\n    kind\\n    name\\n    description\\n    fields(includeDeprecated: true) {\\n      name\\n      description\\n      args {\\n        ...InputValue\\n      }\\n      type {\\n        ...TypeRef\\n      }\\n      isDeprecated\\n      deprecationReason\\n    }\\n    inputFields {\\n      ...InputValue\\n    }\\n    interfaces {\\n      ...TypeRef\\n    }\\n    enumValues(includeDeprecated: true) {\\n      name\\n      description\\n      isDeprecated\\n      deprecationReason\\n    }\\n    possibleTypes {\\n      ...TypeRef\\n    }\\n  }\\n\\n  fragment InputValue on __InputValue {\\n    name\\n    description\\n    type { ...TypeRef }\\n    defaultValue\\n  }\\n\\n  fragment TypeRef on __Type {\\n    kind\\n    name\\n    ofType {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n          ofType {\\n            kind\\n            name\\n            ofType {\\n              kind\\n              name\\n              ofType {\\n                kind\\n                name\\n                ofType {\\n                  kind\\n                  name\\n                }\\n              }\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n"}' } }
```

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

I'm using Express and Apollo Server as the server. The exact query above works fine without all the `\\n`.

**Comment by Experiment8** [comment]
Same problem here, would be nice to have a solution to this.

**Comment by jimkyndemeyer** [comment]
Please setup a codesandbox or similar which reproduces the issue and link it here.

**Comment by Experiment8** [comment]
Gonna do that. In the meantime I can share my `graphql.config.json`, I have this:

```
{
  "schema": {
    "request": {
      "url" : "http://myhost/query/data",
      "method" : "POST",
      "postIntrospectionQuery" : true,
      "options" : {
        "headers": {
          "user-agent" : "JS GraphQL"
        }
      }
    }
  }
}
```
The plugin is able to connect but I get the 400 from GraphQL server because of the `\\n` in the query:
```
Error loading schema from 'http://myhost/query/data' Response {
  statusCode: 400,
  headers: 
   { connection: 'close',
     date: 'Tue, 30 Oct 2018 09:13:17 GMT',
     'content-type': 'application/json',
     'content-length': '224' },
  body: <Buffer 7b 22 65 72 72 6f 72 63 6f 64 65 22 3a 34 30 36 2c 22 6d 65 73 73 61 67 65 22 3a 22 72 65 71 75 65 73 74 20 74 6f 20 43 68 61 6f 73 20 65 6e 64 70 6f ... >,
  url: undefined } { url: 'http://myhost/query/data',
  method: 'POST',
  postIntrospectionQuery: true,
  options: 
   { headers: 
      { 'user-agent': 'JS GraphQL',
        'Content-Type': 'application/json',
        'Content-Length': 1550,
        'Accept-Encoding': 'gzip,deflate' },
     body: '{"query":"\\n  query IntrospectionQuery {\\n    __schema {\\n      queryType { name }\\n      mutationType { name }\\n      subscriptionType { name }\\n      types {\\n        ...FullType\\n      }\\n      directives {\\n        name\\n        description\\n        locations\\n        args {\\n          ...InputValue\\n        }\\n      }\\n    }\\n  }\\n\\n  fragment FullType on __Type {\\n    kind\\n    name\\n    description\\n    fields(includeDeprecated: true) {\\n      name\\n      description\\n      args {\\n        ...InputValue\\n      }\\n      type {\\n        ...TypeRef\\n      }\\n      isDeprecated\\n      deprecationReason\\n    }\\n    inputFields {\\n      ...InputValue\\n    }\\n    interfaces {\\n      ...TypeRef\\n    }\\n    enumValues(includeDeprecated: true) {\\n      name\\n      description\\n      isDeprecated\\n      deprecationReason\\n    }\\n    possibleTypes {\\n      ...TypeRef\\n    }\\n  }\\n\\n  fragment InputValue on __InputValue {\\n    name\\n    description\\n    type { ...TypeRef }\\n    defaultValue\\n  }\\n\\n  fragment TypeRef on __Type {\\n    kind\\n    name\\n    ofType {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n          ofType {\\n            kind\\n            name\\n            ofType {\\n              kind\\n              name\\n              ofType {\\n                kind\\n                name\\n                ofType {\\n                  kind\\n                  name\\n                }\\n              }\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n"}' } }
```
I will get back with the link ASAP, thanks!

**Comment by Experiment8** [comment]
Sorry for the late reply, how do I set a Code sandbox for and IDE with a Java plugin, AFAIK is not as easy as for JS code.

**Comment by jimkyndemeyer** [comment]
Hi again.

Please try https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-1

Let me know if you have any issues.

Best regards,
Jim.

**Comment by Experiment8** [comment]
Ehy!

Thanks for the update, unfortunately it doesn't seem to work yet, now I don't even know what's the problem, the logs are not giving me any info about the http status of the request:

This is the stack trace

```
java.lang.IllegalArgumentException: Expected data key to be present in query result. Got keys: [status, statusCode, message]
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper.printIntrospectionJsonAsGraphQL(GraphQLIntrospectionHelper.java:234)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper$2.lambda$run$0(GraphQLIntrospectionHelper.java:160)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

It would be nice to know what's in `status`, `statusCode` and `message`, otherwise is pretty hard to debug.

**Comment by jimkyndemeyer** [comment]
Hi Roberto.

You should be able to switch to the GraphQL Query result tab to see the server response.

Best regards,
Jim.

**Comment by Experiment8** [comment]
Ah you right, sorry my mistake.
I saw the error, apparently operation name is not valid, :

```
{
  "status": "error",
  "statusCode": 400,
  "message": "Invalid Request: graphql.execution.UnknownOperationException: Unknown operation named 'NONE'."
}
```
Do I need to specify something in the `config` file?

**Comment by jimkyndemeyer** [comment]
@Experiment8 The introspection query that this plugin sends by default is named "IntrospectionQuery": 
 https://github.com/graphql-java/graphql-java/blob/bd9240c15fbf2eb00b2ad92b08006772e93dc387/src/main/java/graphql/introspection/IntrospectionQuery.java#L5-L6

According to the graphql-java docs you should only see that error when multiple operations (query, mution, subscription) are present: https://github.com/graphql-java/graphql-java/blob/bd9240c15fbf2eb00b2ad92b08006772e93dc387/src/main/java/graphql/execution/UnknownOperationException.java#L6-L12

Have you configured an invalid custom introspection query in the plugin GraphQL settings page?

**Comment by Experiment8** [comment]
Ehy!

Thanks for the answer, this is my config file, pretty standard:

```
{
  "name": "Main schema",
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "https://myservice.com/query/data",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

While as per `operationName` I need to check. What I can see is that the introspection works fine with `GraphiQL` tool, but for some reason it doesn't in Webstorm.

Also I tried to add operationName `IntrospectionQuery`, and I get back a syntax error on first char:

```
{
  "errors": [
    {
      "message": "Invalid Syntax",
      "locations": [
        {
          "line": 1,
          "column": 0
        }
      ]
    }
  ]
}
```

Any idea?

**Comment by jimkyndemeyer** [comment]
@Experiment8 I assume you entered the operation name into the this config screen in WebStorm:

![image](https://user-images.githubusercontent.com/15837712/56230893-803a6580-607d-11e9-9d9f-b901d14da1ae.png)

An operation name alone is not a valid query, hence the "Invalid syntax" response from your endpoint. You should make sure that the "Introspection Query" text field is completely empty to make WebStorm use the default query that's named "IntrospectionQuery".

You could try and clone https://github.com/jimkyndemeyer/graphql-config-examples it has an example of how to introspect in the `remote-schema-introspection` folder. If you get that working you could simply swap out the endpoint API URL with your own to see if that works. Set a breakpoint in your endpoint and see both the incoming introspection query and how your endpoint handles it.

I don't have any other ideas as to what's going on here. If introspection was broken there'd likely be a lot of other issues reported on this.

**Comment by Experiment8** [comment]
Ehy,

Thanks for helping out, I'm afraid I can't find a solution to the issue, I'll drop it for now, just a recap of my status:

Config (Is exactly the one in the examples with different endpoint)
```
{
  "name": "Remote Schema",
  "schemaPath": "remote-schema.graphql",
  "extensions": {
    "endpoints": {
      "Remote GraphQL Endpoint": {
        "url": "https://myservice/query/data",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

Configuration of the plugin:
![image](https://user-images.githubusercontent.com/3374223/56274959-131be400-6100-11e9-9ea2-f640cf60d79a.png)

Error:
```
{
  "status": "error",
  "statusCode": 400,
  "message": "Invalid Request: graphql.execution.UnknownOperationException: Unknown operation named 'NONE'."
}
```

**Comment by Mayur1995** [comment]
Below worked for me :
1) Manually get the introspection response of the remote graphql server ---> schema.json
2) The only difference here is, I set introspection to false :
` {
  "name": "Untitled GraphQL Schema",
  "schemaPath": "schema.json",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "https://api.xvzserver.com/v1/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": false
      }
    }
  }
}`
3) Ready to execute/craft any query based on the schema and run against Xyz server.

I hope this will put some light on this.

**Comment by ZMobile** [comment]
I appreciate your contributions @jimkyndemeyer from v2 of the Intellij GraphQL plugin. Particularly the enhancement allowing for the ability to have multiple GraphQl endpoints and schemas in a multi module Maven project.

I'm currently putting it to the test for such a structure using spring boot and am facing some new problems. 

Here are the graphQL maven dependencies I'm utilizing:

```
<dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>8.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java-tools</artifactId>
            <version>5.2.4</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java-servlet</artifactId>
            <version>6.1.2</version>
        </dependency>
```


The Schema and Project Structure reports that the schema is being properly parsed and there are no schema errors reported, and Spring Boot initializes without a hitch. However, when I run a scratch file query on the default endpoint:

```http://localhost:8080/graphql```,

I get the following error:

```
A valid schema could not be built using the introspection result. Error: expected `data` key to be present in query result.
```

I am posting this here because this appears to be the only forum addressing the corresponding stack trace error:

```
java.lang.IllegalArgumentException: Expected `data` key to be present in query result.
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionService.getIntrospectionSchemaData(GraphQLIntrospectionService.java:261)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionService.printIntrospectionAsGraphQL(GraphQLIntrospectionService.java:195)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionService$IntrospectionQueryTask.run(GraphQLIntrospectionService.java:475)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Furthermore, the graphQL endpoint response is (different from the one mentioned here):

```
{
  "timestamp": 1607557997598,
  "status": 401,
  "error": "Unauthorized",
  "message": "Full authentication is required to access this resource",
  "path": "/graphql"
}
```

Any insight on why this might be happening would be very much appreciated. I'm currently doing what I can to further understand and potentially solve this issue.

**Comment by jimkyndemeyer** [comment]
@ZMobile The error seems to indicate that you need to provide credentials via your config file, e.g. a variantion of what's needed to use the GitHub API: https://github.com/jimkyndemeyer/graphql-config-examples/blob/b417cbc065f8dbcbbef83cb727b616976f731f7f/github-api-v4/.graphqlconfig#L9 Your project might need to have it configured differently for Spring boot to authenticate.

**Comment by ZMobile** [comment]
It seems you are right. I tested a regular REST controller and it appears it is my spring security configuration that is flawed, as its rejecting all requests regardless of whether or not they should be authorized. It's no wonder no one else is having this problem, my apologies, and thanks for your quick response.
