### ISSUE TITLE
Missing Windows Line Ending support

### ISSUE THREAD

**Issue by jeggy** [jimkyndemeyer/js-graphql-intellij-plugin#191]
## Before you create the issue
I have a graphql server built with Kotlin, Ktor and KGraphQL. Example project: https://github.com/jeggy/ktorgraphql

## Version and Environment Details
__Operation system__: Windows 10
__Node.js__: 8.11.1
__Kotlin__: 1.3.10-release-IJ2018.2-1
__Plugin version__: 1.7.2

### Java Version 
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

### IDE name and version
IntelliJ IDEA 2018.2.6 (Ultimate Edition)
Build #IU-182.5107.16, built on November 6, 2018
Licensed to _me_
Subscription is active until December 15, 2018
JRE: 1.8.0_152-release-1248-b22 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

## Expected Behaviour
Be able to read any line endings returned from the server

## Actual Behaviour
Hangs and then crashes with the Stacktrace provided below

## Stacktrace
java.lang.AssertionError: Wrong line separators: '{\r\n  \"data\"...' at offset 1
	at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2688)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:675)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:597)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$setText$3(DocumentImpl.java:1051)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:139)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:97)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:87)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:73)
	at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:1056)
	at com.intellij.lang.jsgraphql.ide.project.JSGraphQLLanguageUIProjectService.lambda$null$8(JSGraphQLLanguageUIProjectService.java:471)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1038)
	at com.intellij.lang.jsgraphql.ide.project.JSGraphQLLanguageUIProjectService.lambda$null$9(JSGraphQLLanguageUIProjectService.java:469)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ForsakenHarmony** [comment]
Valid issue, but there's no reason to not use unix style line endings

**Comment by mattythebatty** [comment]
I'm also experiencing this issue whilst trying to dump the response of a third party

**Comment by jimkyndemeyer** [comment]
Fixed in v1.7.3 pending JetBrains approval.
