### ISSUE TITLE
Some schema can cause the plugin to throw StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by zh217** [jimkyndemeyer/js-graphql-intellij-plugin#198]
## Version and Environment Details
__Operation system__: Windows 10 (I tried a Mac also, same issue)

__IDE name and version__: WebStorm 2018.3.1 (IntelliJ IDEA has the same problem)

__Plugin version__: 1.7.2

## Expected Behaviour
Plugin should work

## Actual Behaviour
Plugin throws StringIndexOutOfBoundException and rendering the IDE unusable

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Just load this almost-empty repo and the error will occur:

[https://github.com/zh217/js-graphql-plugin-error](https://github.com/zh217/js-graphql-plugin-error)

The actual error encountered:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 72281
	at java.lang.String.substring(String.java:1963)
	at com.intellij.lang.jsgraphql.lexer.JSGraphQLLexer.fetchTokensFromLanguageService(JSGraphQLLexer.java:106)
	at com.intellij.lang.jsgraphql.lexer.JSGraphQLLexer.start(JSGraphQLLexer.java:71)
	at com.intellij.lexer.Lexer.start(Lexer.java:47)
	at com.intellij.lang.impl.TokenSequence$Builder.performLexing(TokenSequence.java:67)
	at com.intellij.lang.impl.PsiBuilderImpl.performLexing(PsiBuilderImpl.java:188)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:161)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:115)
	at com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:37)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:73)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:192)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:191)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:245)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$ASTTreeGuide.getFirstChild(RecursiveTreeElementWalkingVisitor.java:48)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$ASTTreeGuide.getFirstChild(RecursiveTreeElementWalkingVisitor.java:35)
	at com.intellij.util.WalkingState.next(WalkingState.java:73)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:61)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:86)
	at com.intellij.psi.impl.GeneratedMarkerVisitor.visitNode(GeneratedMarkerVisitor.java:28)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:81)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:130)
	at com.intellij.psi.impl.PsiFileFactoryImpl.markGenerated(PsiFileFactoryImpl.java:228)
	at com.intellij.psi.impl.PsiFileFactoryImpl.trySetupPsiForFile(PsiFileFactoryImpl.java:130)
	at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java:88)
	at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java:73)
	at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java:67)
	at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java:61)
	at com.intellij.lang.jsgraphql.schema.ide.project.JSGraphQLSchemaLanguageProjectService.getOrCreateSchemaFileElements(JSGraphQLSchemaLanguageProjectService.java:630)
	at com.intellij.lang.jsgraphql.schema.ide.project.JSGraphQLSchemaLanguageProjectService.lambda$onProcessHandlerTextAvailable$0(JSGraphQLSchemaLanguageProjectService.java:387)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jimkyndemeyer** [comment]
Hi Ziyang.

Thanks for using the plugin.

Please try https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-1

Let me know if you have any issues.

Best regards,
Jim.
