### ISSUE TITLE
Plugin doesn't support self signed certificate

### ISSUE THREAD

**Issue by daryn-k** [jimkyndemeyer/js-graphql-intellij-plugin#212]
I really like this plugin, but can't work with it after turn on HTTPS. It throws this error:

```
{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' } 
```
I have no idea how to use some "schema in file option".

**Comment by vepanimas** [comment]
Fixed in https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/435.
