### ISSUE TITLE
[v2] GitHub v4 - Directive unknown argument type '%s'. This should have been validated before.

### ISSUE THREAD

**Issue by orangeloops** [jimkyndemeyer/js-graphql-intellij-plugin#233]
v2.0.0-end-of-beta

WebStorm 2019.1
Build #WS-191.6183.63, built on March 21, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

{
  "name": "GitHub v4 Schema",
  "schemaPath": "github.schema.graphql",
  "extensions": {
    "endpoints": {
      "GitHub": {
        "url": "https://api.github.com/graphql",
        "introspect": true,
        "headers": {
          "Authorization": "Bearer ${env:GITHUB_ACCESS_TOKEN}"
        }
      }
    }
  }
}

graphql.AssertException: Directive unknown argument type '%s'. This should have been validated before.
	at graphql.schema.idl.ArgValueOfAllowedTypeChecker.lambda$checkArgValueMatchesAllowedTypeName$0(ArgValueOfAllowedTypeChecker.java:118)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at graphql.schema.idl.ArgValueOfAllowedTypeChecker.checkArgValueMatchesAllowedTypeName(ArgValueOfAllowedTypeChecker.java:118)
	at graphql.schema.idl.ArgValueOfAllowedTypeChecker.checkArgValueMatchesAllowedType(ArgValueOfAllowedTypeChecker.java:97)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.lambda$checkDirectiveArguments$23(SchemaTypeDirectivesChecker.java:153)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.checkDirectiveArguments(SchemaTypeDirectivesChecker.java:147)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.lambda$checkDirectives$22(SchemaTypeDirectivesChecker.java:130)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.checkDirectives(SchemaTypeDirectivesChecker.java:122)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.lambda$checkFieldsDirectives$21(SchemaTypeDirectivesChecker.java:114)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.checkFieldsDirectives(SchemaTypeDirectivesChecker.java:113)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.checkDirectives(SchemaTypeDirectivesChecker.java:96)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.lambda$checkTypeDirectives$12(SchemaTypeDirectivesChecker.java:75)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.checkTypeDirectives(SchemaTypeDirectivesChecker.java:75)
	at graphql.schema.idl.SchemaTypeChecker.checkTypeRegistry(SchemaTypeChecker.java:90)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:268)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:246)
	at graphql.schema.idl.UnExecutableSchemaGenerator.makeUnExecutableSchema(UnExecutableSchemaGenerator.java:28)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.lambda$getSchemaWithErrors$1(GraphQLTypeDefinitionRegistryServiceImpl.java:72)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.getSchemaWithErrors(GraphQLTypeDefinitionRegistryServiceImpl.java:69)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLConfigSchemaNode.<init>(GraphQLConfigSchemaNode.java:82)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasRootNode.getChildren(GraphQLSchemasRootNode.java:48)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$0(GraphQLSchemasPanel.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:945)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$1(GraphQLSchemasPanel.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jimkyndemeyer** [comment]
Thanks for testing the plugin.

I just tested introspection against the GitHub API and it was succesful.

Please add the steps to reproduce. Otherwise this issue isn't actionable.

Best regards,
Jim.

**Comment by danielg2002** [comment]
I just uninstall the beta and reinstall it from the store, and it's working.

Thanks,
Daniel

**Comment by jimkyndemeyer** [comment]
Closing this as it's not actionable without steps to reproduce. Please reopen once that's added.
