### ISSUE TITLE
Schema generation from introspection result fails

### ISSUE THREAD

**Issue by dllx** [jimkyndemeyer/js-graphql-intellij-plugin#248]
## Version and Environment Details
macOS 10.13.6

IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019

JS GraphQL v2.1.0

## Expected Behaviour

Clicking the green arrow in the `.graphqlconfig` file next to the `"url":` row of my endpoint definition, I expect an introspection query to be run whose result is then turned into a GraphQL schema.

## Actual Behaviour

The introspection query runs, it returns a result, but then an error popup says
```
A valid schema could not be built using the introspection result: Introspection query returned errors: null
```

The introspection result can be seen when clicking on the `Query result` tab of the GraphQL tool window.

Clicking on `Stack trace` in the event popup gives
```
java.lang.IllegalArgumentException: Introspection query returned errors: null
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper.printIntrospectionJsonAsGraphQL(GraphQLIntrospectionHelper.java:231)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper$2.lambda$run$0(GraphQLIntrospectionHelper.java:160)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:690)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
I can attach the result of the introspection query if it's really needed, but as it is nearly 2000 lines long with all the builtin GraphQL types, I omit that for now. Maybe the error is already obvious enough to analyze.

**Comment by jimkyndemeyer** [comment]
Hi Dirk.

Thanks for using the plugin.

This exception is thrown when your GraphQL endpoint returns an `errors` property in response to the introspection. In this case it appears to return a `null` array which is not in line with the GraphQL spec: https://graphql.github.io/graphql-spec/June2018/#sec-Errors

"If no errors were encountered during the requested operation, the errors entry should not be present in the result."

I think you'll likely need to log an issue with the GraphQL framework that you're using to make it aligned with the spec.

As a workaround you could look at https://github.com/prisma/get-graphql-schema or a similar tool to generate a graphql file that the plugin can use to discover your schema.

Best regards,
Jim.

**Comment by dllx** [comment]
Thanks Jim, I'll look into it.
Many sincere thanks for this awesome plugin!

**Comment by dlindberg** [comment]
Thanks, this just solved an issue I was having too. It might be helpful to add a note on the "Working with GraphQL Endpoints" section of the Docs, that if you have an API you are using that you don't control (can't fix) that trows error when you try and generate the schema with introspection that you can resolve the issue in this way. It took me longer than I care to admit to find this is issue and get things up and running.

Thanks for building a supper helpful plugin, as good as GraphiQL might be, this is really so much better...
