### ISSUE TITLE
Introspection fails with graphql-java backend due to "Introspection query returned errors: []"

### ISSUE THREAD

**Issue by hameno** [jimkyndemeyer/js-graphql-intellij-plugin#272]
## Version and Environment Details
__Operation system__: Windows 10

__IDE name and version__: Android Studio 3.5 RC1

__Plugin version__: 2.2.0

## Expected Behaviour
Introspection works

## Actual Behaviour
Introspection fails

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Use server with graphql-java backend. This will return a full result, where errors is an empty array.
The code at GraphQLIntrospectionHelper#printIntrospectionJsonAsGraphQL line 249 does not check if the array is empty or not. An empty array signals no errors but this method just errors out.

```
java.lang.IllegalArgumentException: Introspection query returned errors: []
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper.printIntrospectionJsonAsGraphQL(GraphQLIntrospectionHelper.java:231)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper$2.lambda$run$0(GraphQLIntrospectionHelper.java:160)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by jimkyndemeyer** [comment]
Hi Philip.

Thanks for using the plugin.

I reviewed the GraphQL spec https://graphql.github.io/graphql-spec/June2018/#sec-Errors

It states that:
> If no errors were encountered during the requested operation, the errors entry should not be present in the result.

With that in mind the plugin follows the spec in its current implementation. I'm reluctant to change this to a behaviour that deviates from the spec.

We also use graphql-java in my team and I see that we null out the errors list if it's empty before returning the JSON response. This was due to the Relay client throwing even with the empty array as per the spec.

**Comment by hameno** [comment]
So it looks like a bug in the graphql-java library?

**Comment by jimkyndemeyer** [comment]
Not exactly. We had our own Gson JSON serialization in play after calling graphql-java which is where made the change.

**Comment by hameno** [comment]
hmm, okay, let me see if I can fix our backend accordingly.

**Comment by jimkyndemeyer** [comment]
Looks like they have a utility to help with this now:
https://github.com/graphql-java/graphql-java/blob/527c587598e66a3b0669584efe441cfd8340dfca/src/main/java/graphql/ExecutionResultImpl.java#L76-L80

**Comment by hameno** [comment]
Yes, just found this aswell. Thanks!

**Comment by malbanese** [comment]
@jimkyndemeyer 
Would you be willing to at least have a togglable option to allow out of spec errors? I'm in a situation where a graphql server is sending the empty error array out of spec, and I'm not able to address it.

It also looks like they added robustness support inside apollo-client for this:
https://github.com/apollographql/apollo-client/commit/eaeabe28b4bd32152d44364e7eb9f0d3d7275223

**Comment by jimkyndemeyer** [comment]
@malbanese Sounds like a good improvement.

Due to other commitments I can't carve out time to look at it, so would be great with a PR.

If that's out of scope, a temporary workaround is to use a graphql cli to pull down the introspection result into a `schema.json` file, delete the `errors` field and point to that file in the `schemaPath` of your graphql config.

See `schema:download` in  https://www.apollographql.com/docs/ios/downloading-schema/

Hope that helpful.

Best regards,
Jim

**Comment by malbanese** [comment]
@jimkyndemeyer Sounds great. I'm currently using the error workaround, I'll see about getting a PR with the enhancement. 

Thanks!
Michael
