### ISSUE TITLE
Crashes with WebStrom 2019.3

### ISSUE THREAD

**Issue by koresar** [jimkyndemeyer/js-graphql-intellij-plugin#301]
I just upgraded the WebStorm from 2019.2 to 2019.3. The plugin does not work any more.

```
graphql.AssertException: Directive unknown argument type '%s'. This should have been validated before.
	at graphql.schema.idl.ArgValueOfAllowedTypeChecker.lambda$checkArgValueMatchesAllowedTypeName$0(ArgValueOfAllowedTypeChecker.java:118)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at graphql.schema.idl.ArgValueOfAllowedTypeChecker.checkArgValueMatchesAllowedTypeName(ArgValueOfAllowedTypeChecker.java:118)
	at graphql.schema.idl.ArgValueOfAllowedTypeChecker.checkArgValueMatchesAllowedType(ArgValueOfAllowedTypeChecker.java:97)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.lambda$checkDirectiveArguments$23(SchemaTypeDirectivesChecker.java:153)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.checkDirectiveArguments(SchemaTypeDirectivesChecker.java:147)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.lambda$checkDirectives$22(SchemaTypeDirectivesChecker.java:130)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.checkDirectives(SchemaTypeDirectivesChecker.java:122)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.lambda$checkFieldsDirectives$21(SchemaTypeDirectivesChecker.java:114)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.checkFieldsDirectives(SchemaTypeDirectivesChecker.java:113)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.checkDirectives(SchemaTypeDirectivesChecker.java:96)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.lambda$checkTypeDirectives$12(SchemaTypeDirectivesChecker.java:75)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at graphql.schema.idl.SchemaTypeDirectivesChecker.checkTypeDirectives(SchemaTypeDirectivesChecker.java:75)
	at graphql.schema.idl.SchemaTypeChecker.checkTypeRegistry(SchemaTypeChecker.java:90)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:259)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:237)
	at graphql.schema.idl.UnExecutableSchemaGenerator.makeUnExecutableSchema(UnExecutableSchemaGenerator.java:28)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.lambda$getSchemaWithErrors$1(GraphQLTypeDefinitionRegistryServiceImpl.java:72)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.getSchemaWithErrors(GraphQLTypeDefinitionRegistryServiceImpl.java:69)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLConfigSchemaNode.<init>(GraphQLConfigSchemaNode.java:82)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasRootNode.getChildren(GraphQLSchemasRootNode.java:48)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$0(GraphQLSchemasPanel.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:796)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$1(GraphQLSchemasPanel.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## Version and Environment Details
__Operation system__: MacOS

__IDE name and version__: WebStrom 2019.3

__Plugin version__: 2.2.0

## Expected Behaviour

Show syntax highlight as before.

@jimkyndemeyer is the information above enough for you to reproduce?

**Comment by jimkyndemeyer** [comment]
Hi Vasyl.

From the stack trace this doesn't indicate any incompatibility with the new WebStorm itself.

I think the issue is that graphql-java is throwing an AssertionException due to some potentially invalid use of directives. If I recall correctly, the plugin does catch GraphQLExceptions, but I may have missed that they also use assertions.

I don't think I'll be able to reproduce this without an example schema that demonstrates the issue. Could you please try with a blank project, and see whether you can get a single graphql file working with WS 2019.3?

Best regards,
Jim.

**Comment by koresar** [comment]
So I tried reproducing it. However, after restarting the IDE the bug disappeared. I assume it's a [Heisenbug](https://www.webopedia.com/TERM/H/heisenbug.html).

Will reopen this issue (or create a new one) if I have a reproducible something.

Thanks.
