### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by jazzdragon** [jimkyndemeyer/js-graphql-intellij-plugin#317]
## Version and Environment Details
__Operation system__:  Mac OS 10.15.3

__IDE name and version__:  RubyMine 2019.3.3

__Plugin version__:  2.3.0

## Expected Behaviour

Updated RubyMine to 2019.3.3, plugin should keep working

## Actual Behaviour

Getting this error:

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'relPath' of com/intellij/openapi/vfs/VirtualFile.findFileByRelativePath must not be null
	at com.intellij.openapi.vfs.VirtualFile.$$$reportNull$$$0(VirtualFile.java)
	at com.intellij.openapi.vfs.VirtualFile.findFileByRelativePath(VirtualFile.java)
	at com.intellij.lang.jsgraphql.ide.project.graphqlconfig.GraphQLConfigPackageSet.lambda$matchesGlobs$2(GraphQLConfigPackageSet.java:152)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.intellij.lang.jsgraphql.ide.project.graphqlconfig.GraphQLConfigPackageSet.matchesGlobs(GraphQLConfigPackageSet.java:151)
	at com.intellij.lang.jsgraphql.ide.project.graphqlconfig.GraphQLConfigPackageSet.lambda$includesVirtualFile$1(GraphQLConfigPackageSet.java:143)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.lang.jsgraphql.ide.project.graphqlconfig.GraphQLConfigPackageSet.includesVirtualFile(GraphQLConfigPackageSet.java:131)
	at com.intellij.lang.jsgraphql.ide.project.graphqlconfig.GraphQLConfigPackageSet.contains(GraphQLConfigPackageSet.java:89)
	at com.intellij.psi.search.GlobalSearchScopesCore$FilterScopeAdapter.contains(GlobalSearchScopesCore.java:83)
	at com.intellij.psi.search.GlobalSearchScope$UnionScope.lambda$contains$0(GlobalSearchScope.java:517)
	at com.intellij.util.containers.ContainerUtil.find(ContainerUtil.java:954)
	at com.intellij.psi.search.GlobalSearchScope$UnionScope.contains(GlobalSearchScope.java:517)
	at com.intellij.psi.search.GlobalSearchScope$IntersectionScope.contains(GlobalSearchScope.java:422)
	at com.intellij.psi.search.GlobalSearchScope$IntersectionScope.contains(GlobalSearchScope.java:422)
	at com.intellij.psi.search.GlobalSearchScope.accept(GlobalSearchScope.java:71)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processValuesInScope$14(FileBasedIndexImpl.java:962)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processValueIterator$15(FileBasedIndexImpl.java:985)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$null$11(FileBasedIndexImpl.java:910)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:242)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processExceptions$12(FileBasedIndexImpl.java:910)
	at com.intellij.util.indexing.IndexAccessValidator.validate(IndexAccessValidator.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:910)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:984)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:955)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:852)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:840)
	at com.intellij.psi.search.FileNameIndexServiceImpl.processFilesWithFileType(FileNameIndexServiceImpl.java:47)
	at com.intellij.psi.search.FileTypeIndex.processFiles(FileTypeIndex.java:60)
	at com.intellij.lang.jsgraphql.schema.SchemaIDLTypeDefinitionRegistry.lambda$getRegistryWithErrors$4(SchemaIDLTypeDefinitionRegistry.java:223)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.lang.jsgraphql.schema.SchemaIDLTypeDefinitionRegistry.getRegistryWithErrors(SchemaIDLTypeDefinitionRegistry.java:102)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.lambda$getRegistryWithErrors$0(GraphQLTypeDefinitionRegistryServiceImpl.java:58)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.getRegistryWithErrors(GraphQLTypeDefinitionRegistryServiceImpl.java:57)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.lambda$getSchemaWithErrors$1(GraphQLTypeDefinitionRegistryServiceImpl.java:70)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.getSchemaWithErrors(GraphQLTypeDefinitionRegistryServiceImpl.java:69)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLConfigSchemaNode.<init>(GraphQLConfigSchemaNode.java:82)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLConfigSchemaNode$GraphQLConfigProjectsNode.lambda$buildChildren$0(GraphQLConfigSchemaNode.java:176)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLConfigSchemaNode$GraphQLConfigProjectsNode.buildChildren(GraphQLConfigSchemaNode.java:177)
	at com.intellij.ui.treeStructure.CachingSimpleNode.getChildren(CachingSimpleNode.java:39)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$0(GraphQLSchemasPanel.java:130)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:796)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$1(GraphQLSchemasPanel.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jimkyndemeyer** [comment]
Hi Alon.

Thanks for using the plugin.

I just installed the specified RubyMine version, but can't reproduce the issue.

To make this issue actionable, please attach a minimal project that reproduces the issue.

Best regards,
Jim.

**Comment by jazzdragon** [comment]
Sorry my bad, turns out I also changed my `.graphqlconfig` and had an extra comma in there.
