### ISSUE TITLE
graphql.AssertException:  type definition for type 'TypeName{name='String'}' not found

### ISSUE THREAD

**Issue by min9nim** [jimkyndemeyer/js-graphql-intellij-plugin#325]
## Before you create the issue
- Please search the existing issues at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc before opening a new issue.
- Read the FAQ at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#faq
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions.

## Version and Environment Details
__Operation system__:  MacOS Catalina 10.15.3

__IDE name and version__: WebStorm 2019.03.03
```
WebStorm 2019.3.3
Build #WS-193.6494.34, built on February 11, 2020
Licensed to JJSOFT / mingu song
Subscription is active until March 28, 2020
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 989M
Cores: 8
Registry: js.debugger.webconsole=false
Non-Bundled Plugins: com.intellij.lang.jsgraphql, com.wakatime.intellij.plugin, ru.adelf.idea.dotenv
```

__Plugin version__: 2.4.0

## Expected Behaviour
update schema

## Actual Behaviour
GraphQL Introspection Error

```
graphql.AssertException:  type definition for type 'TypeName{name='String'}' not found
	at graphql.Assert.assertTrue(Assert.java:76)
	at graphql.schema.idl.SchemaGenerator$BuildContext.getTypeDefinition(SchemaGenerator.java:162)
	at graphql.schema.idl.SchemaGenerator.buildInputType(SchemaGenerator.java:456)
	at graphql.schema.idl.SchemaGenerator.lambda$null$1(SchemaGenerator.java:401)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirectiveArgumentFromDefinition(SchemaGeneratorHelper.java:328)
	at graphql.schema.idl.SchemaGeneratorHelper.lambda$buildDirectiveFromDefinition$9(SchemaGeneratorHelper.java:317)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirectiveFromDefinition(SchemaGeneratorHelper.java:318)
	at graphql.schema.idl.SchemaGenerator.lambda$buildAdditionalDirectives$2(SchemaGenerator.java:402)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at graphql.schema.idl.SchemaGenerator.buildAdditionalDirectives(SchemaGenerator.java:400)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchemaImpl(SchemaGenerator.java:278)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:271)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:243)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper.buildIntrospectionSchema(GraphQLIntrospectionHelper.java:318)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper.printIntrospectionJsonAsGraphQL(GraphQLIntrospectionHelper.java:282)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper$2.lambda$run$0(GraphQLIntrospectionHelper.java:162)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

click `Get Graphql Schema ~~` and error is occured

![image](https://user-images.githubusercontent.com/6068828/77610508-3e40c180-6f66-11ea-854e-d4efa556b6ed.png)

**Comment by min9nim** [comment]
it works before upgrade `js-graphql` pluings to 2.4.0.

help me please.

**Comment by jimkyndemeyer** [comment]
Hi,

Thanks for using the plugin.

From the stack trace it appears that the assertion error is thrown when it builds up a specific directive definition.

I tried to define a directive which has a 'String' argument:

```graphql
directive @foo(bar: String) on OBJECT
```

But this doesn't throw an error, so I'll need the directive definitions from your schema to make progress on this. The preferred format is as GraphQL SDL as written above. As an alternative you should see the introspection result as JSON in the GraphQL "Query result" tool window tab after you run the introspection. Please paste or attach the directive definitions to this issue.

As a temporary workaround you can revert back to 2.3.0 using the download button next to the header at https://plugins.jetbrains.com/plugin/8097-js-graphql/update/74453 and then using the "Install plugin from file" options in WebStorm.

Best regards,
Jim.

**Comment by min9nim** [comment]
Thank you for your kind answer.

I tried to attach the content. But Today, the problem does not occur and it works normally. (I don't know why)

I'll share the content again in case of problems later.

Thank you.

**Comment by GeyseR** [comment]
Hi @jimkyndemeyer,

it looks like I have very similar issue with my schema when it is parsed by the plugin (which is really great btw and I cannot live without it anymore)

Not sure when it started, probably after updating to PyCharm 2020.1, but unfortunately the parsing of my schema has started to fail with the following errors:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/1364479/80279890-f51c9280-8708-11ea-8570-042bd9d5c013.png">

I was able to reproduce the problem with very basic graphql schema definition with just one field `field` of type String: [graphql.schema.json.txt](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/4532940/graphql.schema.json.txt) (the txt extension is a workaround for github file upload restrictions and should be removed)

The schema was generated by the `graphene-django` python package (ver 2.9.1)

This schema works on the client though.

Could you please help me identify the source of the problem?

**Comment by jimkyndemeyer** [comment]
Hi Sergey,

I just tried the attached schema in the graphql-config-examples project inside PyCharm CE 2020.1, and it validates:

![issue-325](https://user-images.githubusercontent.com/15837712/80281030-9f47ea80-8708-11ea-9a7b-6ebf08f1c2da.png)

It could be a timing issue in the schema discovery (it's quite complex and multi-threaded).

I see that you're using a json file to store the schema in. I recommend that you switch to using `.graphql` as extension for your schemaPath in your config file. This removes the need for the plugin to convert between JSON and GraphQL SDL which could be part of the issue.

Let me know if that fixes your issue.

Best regards,
Jim.

**Comment by GeyseR** [comment]
Hmm, after converting the schema to graphql format the first error is gone.
the second one is still there:
![image](https://user-images.githubusercontent.com/1364479/80281449-e9829900-8713-11ea-963f-746b2c70dcb7.png)

here is the stacktrace:
```
graphql.AssertException:  type definition for type 'TypeName{name='String'}' not found
	at graphql.Assert.assertTrue(Assert.java:76)
	at graphql.schema.idl.SchemaGenerator$BuildContext.getTypeDefinition(SchemaGenerator.java:162)
	at graphql.schema.idl.SchemaGenerator.buildInputType(SchemaGenerator.java:456)
	at graphql.schema.idl.SchemaGenerator.lambda$null$1(SchemaGenerator.java:401)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirectiveArgumentFromDefinition(SchemaGeneratorHelper.java:328)
	at graphql.schema.idl.SchemaGeneratorHelper.lambda$buildDirectiveFromDefinition$9(SchemaGeneratorHelper.java:317)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirectiveFromDefinition(SchemaGeneratorHelper.java:318)
	at graphql.schema.idl.SchemaGenerator.lambda$buildAdditionalDirectives$2(SchemaGenerator.java:402)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at graphql.schema.idl.SchemaGenerator.buildAdditionalDirectives(SchemaGenerator.java:400)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchemaImpl(SchemaGenerator.java:278)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:271)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:243)
	at graphql.schema.idl.UnExecutableSchemaGenerator.makeUnExecutableSchema(UnExecutableSchemaGenerator.java:28)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.lambda$getSchemaWithErrors$1(GraphQLTypeDefinitionRegistryServiceImpl.java:72)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.getSchemaWithErrors(GraphQLTypeDefinitionRegistryServiceImpl.java:69)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLConfigSchemaNode.<init>(GraphQLConfigSchemaNode.java:82)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasRootNode.getChildren(GraphQLSchemasRootNode.java:48)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$0(GraphQLSchemasPanel.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:869)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$1(GraphQLSchemasPanel.java:125)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jimkyndemeyer** [comment]
This is a long shot, but I'm thinking there's an invisible unicode character somewhere, e.g. from a copy-paste, that is messing up the type lookup for `String`. Could you please try to select all in your schema file, clear the file, and type it manually line by line?

**Comment by GeyseR** [comment]
That what I did initially :)
Another interesting thing is that introspection for the String type works as expected:  Cmd+Click on the String type points me to GraphQL Specification Schema file
If you point me to the place where the validation happen, I will be able to debug it in more details (if it doesn't require to install too much instrumentation though :) )

**Comment by jimkyndemeyer** [comment]
The plugin parses the files into syntax trees, and uses the IntelliJ platform for navigation, which indicates that the type in your schema is actually called "String" and nothing else. But the plugin also needs to provide validation and schema-based completion, which is where it relies on graphql-java to build up a valid schema. Have you tried with other field types, e.g. Int, Float, or Boolean?

It's a mystery why you're seeing this error, but the indication is that it's somehow localized to certain environments since I could not reproduce with PyCharm and your example schema. That unfortunately makes is near impossible for me to debug the issue.

If you're up for, you'll need to checkout the plugin code, and debug it using the gradle "intellij / runIde" task. You should be able to use a trial of IntelliJ IDEA Ultimate in case you don't have a full  license. Then setup a Java Exception breakpoint for the graphql.AssertException class and you should see the debugger halt when the issue occurs.

As an alternative, do you have another machine or a friend/colleague with PyCharm where you can compare environments and somehow eliminate factors that can break this on your machine? If not, re-install of the plugin and PyCharm could also be worth a shot since you had it working previously.

**Comment by GeyseR** [comment]
> Have you tried with other field types, e.g. Int, Float, or Boolean?
hmm, I have interesting results with other standard types. The plugin still shows me ` type definition for type 'TypeName{name='String'}' not found`. When I don't even have a String fields in the schema, like:
```
schema {
  query: Query
}

type Query {
  field1: Int
  field2: Boolean
}
```

regarding the debugging, I'll try to find a time to debug the source of the problem. It will be difficult though, because I have six-years old basic knowledge about Java.

**Comment by GeyseR** [comment]
Unfortunately, the error didn't happen in the clean debugging IntelliJ IDEA Ultimate environment.
Re-installing the plugin fixed the problem.
Thanks for helping 👍
