### ISSUE TITLE
Get schema doesn't work after server added api key

### ISSUE THREAD

**Issue by thanhbinh84** [jimkyndemeyer/js-graphql-intellij-plugin#357]
**Describe the bug**
Get schema doesn't work after server added api key

**To Reproduce**
1. It works properly before, but after server requires api key 
2. Go to 'GraphQL tab'
3. Double click on endpoint 
4. Click Get GraphQL from endpoint 
5. See error 

```
java.lang.IllegalArgumentException: Expected data key to be present in query result. Got keys: [message]
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper.printIntrospectionJsonAsGraphQL(GraphQLIntrospectionHelper.java:224)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionHelper$2.lambda$run$0(GraphQLIntrospectionHelper.java:150)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Expected behavior**
Schema should be updated 

**Version and Environment Details**
Operation system: MacOS 10.15.6
IDE name and version: Android Studio 4.0.1
Plugin version: 2.5.0

**Additional context**
Tried to add header but didn't work, playground is still able to retrieve schema online. 
.graphqlconfig 
```
{
  "name": "Schema",
  "schemaPath": "my.schema.graphql",
  "include": "graphql/**/*.graphql",
  "extensions": {
    "endpoints": {
      "Default": {
        "url": "https://",
        "introspect": false
      },
      "headers": {
        "x-api-key": ""
      }
    }
  }
}
```

**Comment by vepanimas** [comment]
@thanhbinh84 hello! It looks like your config is invalid, headers endpoint should be inside the "Default" key. An example from the config docs:
```
{
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "Default": {
        "url": "https://example.com/graphql",
        "headers": {
          "Authorization": "Bearer ${env:AUTH_TOKEN_ENV}"
        },
        "subscription": {
          "url": "ws://example.com/graphql",
          "connectionParams": {
            "Token": "${env:YOUR_APP_TOKEN}"
          }
        }
      }
    }
  }
}
```
