### ISSUE TITLE
Introspection of Remote Endpoint throws Java exception

### ISSUE THREAD

**Issue by baronyoung** [jimkyndemeyer/js-graphql-intellij-plugin#380]
I'm trying to perform an introspection and graphql SDL file generation locally using the following configuration:
```
{
  "name": "Hasura Tutorial GraphQL Schema",
  "schemaPath": "./schema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "https://hasura.io/learn/graphql",
        "headers": {
          "Authorization": "Bearer <token>"
        },
        "introspect": true
      }
    }
  }
}
```

"token" above and surrounding brackets are replaced by my auth0 token.  Using the above configuration works fine with @graphql-codegen so I know my token, etc. is all working fine.  I would just prefer to use this plugin.

Link to Repo with Reproduction or Steps to Reproduce:
1. Obtain auth token by logging into https://hasura.io/learn/graphql/graphiql
2. Update .graphqlconfig per the above format along with token
3. Restart project and get "perform introspection prompt..."; click it
4. Get the following error:
"GraphQL Introspection Error
				A valid schema could not be built using the introspection result: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $"

**Expected behavior**
Connect to endpoint, perform introspection, and output SDL to "./schema.graphql" file

**Version and Environment Details**
Operation system: MacOS v10.15.6
IDE name and version: Webstorm v2020.1.4
Plugin version: 2.5.0

Additional Context:
I'm trying to step through a Hasura GraphQL with React+Typescript tutorial while replacing the use of the @graphql-codegen library with this plugin.  The link to the tutorial is https://hasura.io/learn/graphql/typescript-react-apollo/queries/4-mapping-types

Thank you.

**Comment by vepanimas** [comment]
@baronyoung hello, this plugin uses [graphql-config v2](https://github.com/kamilkisiela/graphql-config/tree/legacy#specifying-endpoint-info) configuration format now. An expected configuration with the token provided should look like
```
{
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "dev": {
        "url": "https://example.com/graphql",
        "headers": {
          "Authorization": "Bearer ${env:AUTH_TOKEN_ENV}"
        }
      }
    }
  }
}
```

But we definitely need to refine the error handling for this code a bit.

**Comment by baronyoung** [comment]
@vepanimas Thank you but I get the same error using the above method (essentially only change I saw was to use an environment variable as opposed entering the token explicitly).  I did add the "introspect": true statement or it wouldn't perform the introspection.

**Comment by vepanimas** [comment]
@baronyoung oh, I decided that `<token>` is some special syntax to provide a token. Based on the stack trace we can say that this is a JSON parser error. Are there any symbols except alphanumeric in the token?

Note: you can run an introspection query without re-loading an IDE, simple click on the green "play" button on the line with the url property in graphqlconfig file.

**Comment by baronyoung** [comment]
@vepanimas There are periods and hyphens (".", "-").  Other than that it's all alphanumeric.

**Comment by vepanimas** [comment]
Then it shouldn't be related to the token and this error is most likely caused by an unexpected result that the server returns. I'll try to reproduce it, but I need more time, though.

**Comment by baronyoung** [comment]
Ok, thank you.  I added some additional context to the bottom of my original post if that helps with your recreation.

**Comment by vepanimas** [comment]
Also please could you execute the introspection request manually and check if there is any error text after the request in the query tab? It will be very helpful:
![basic-with-dependency-injection –  graphqlconfig 2](https://user-images.githubusercontent.com/10243762/92009767-abe0ed00-ed51-11ea-9d53-06c73c29e202.png)
![gql-error](https://user-images.githubusercontent.com/10243762/92009563-602e4380-ed51-11ea-932c-83d243f6abb0.png)

**Comment by baronyoung** [comment]
Yes, sorry, should have included that.  It's error code: 1010.

**Comment by vepanimas** [comment]
@baronyoung I created a project on Hasura.io and the schema was successfully introspected and saved locally with an exact .graphqlconfig 😞. Actually the error code looks very strange, I can suppose that it's a WebSocket error, but an introspection request is a simple POST. May be something goes wrong on the hasura.io part.

**Comment by baronyoung** [comment]
@vepanimas Did you use the Webstorm JS GraphQL plugin to do the introspection and SDL generation or the @graphql-codegen library described in the Hasura tutorial?    If you used the plugin and it worked I would love to see your .graphqlconfig file.  I didn't have any problem with the library but plugin still doesn't work for me.  Both using the exact same token.

**Comment by vepanimas** [comment]
@baronyoung I didn't use @graphql-codegen, I simply created a project in hasura, opened https://hasura.io/learn/graphql/graphiql, copied the url and the token from here
![GraphiQL Online with Headers _ Built by Hasura - G](https://user-images.githubusercontent.com/10243762/92119647-c45c1080-ee00-11ea-827a-ae27e82669e1.png)
and created this config
![graphqlconfig 2](https://user-images.githubusercontent.com/10243762/92119781-ed7ca100-ee00-11ea-94dd-41e8d62d7b03.png)

**Comment by baronyoung** [comment]
Ok, I just created a fresh project with nothing other than the standard React and Typescript libraries installed and tried it again.  It was successful.  My conclusion is there was something with another library I have installed in my other project that was causing the error.  Thank you for all your help and sorry for raising an issue that was on my end.

**Comment by baronyoung** [comment]
@vepanimas I did a little more troubleshooting on this issue.  What I found is the line:
`"user-agent": "JS GraphQL",`
is required or it will result in the error I reported above.  I don't think this line should be required in all cases as I know it's not needed to authenticate with Hasura for example.  I'll leave it to you whether you want to consider this a bug or not.  I think this may bite others like me though who omit this when it shouldn't be needed.  Thanks again for your help.

**Comment by vepanimas** [comment]
@baronyoung thank you, it's a weird and confusing issue then. I'll check it out.

**Comment by knox** [comment]
I just stumbled upon "error code: 1010" and found this issue so i'd like to add my observation:

Usually i have just one endpoint in my `.graphqlconfig` and things work without problems. Today i added a second endpoint for temporary use and for this endpoint i receive the error. As suggested in this discussion the error goes away when adding a "user-agent" header with arbitrary content.

```
{
  "name": "My Config",
  "schemaPath": "GraphQL/schema.graphql",
  "include": "GraphQL/*.graphql",
  "exclude": "GraphQL/schema.graphql",
  "extensions": {
    "endpoints": {
      "master": {
        "url": "https://master.example.org/graphql",
        "headers": {
          "X-Auth-Token": "abcdefgh"
        },
        "introspect": false
      },
      "other": {
        "url": "https://other.example.org/graphql",
        "headers": {
          "User-Agent": "Issue #380"
          "X-Auth-Token": "abcdefgh"
        },
        "introspect": false
      }
    }
  }
}
```

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionService.parseIntrospectionJson(GraphQLIntrospectionService.java:184)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionService$IntrospectionQueryTask.run(GraphQLIntrospectionService.java:462)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 22 more
```

**Comment by majorhayes** [comment]
> I just stumbled upon "error code: 1010" and found this issue so i'd like to add my observation:
> 
> Usually i have just one endpoint in my `.graphqlconfig` and things work without problems. Today i added a second endpoint for temporary use and for this endpoint i receive the error. As suggested in this discussion the error goes away when adding a "user-agent" header with arbitrary content.
> ...
> ```
> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> ```

I was getting this same error with just 1 remote server configured. I even added a "user-agent" header and it still failed. I changed the header to "User-Agent" and it started working.
