### ISSUE TITLE
java.lang.NullPointerException when optional default value provided in field argument

### ISSUE THREAD

**Issue by rrrix** [jimkyndemeyer/js-graphql-intellij-plugin#412]
**Describe the bug**

```
java.lang.NullPointerException
	at com.intellij.lang.jsgraphql.ide.GraphQLValidationAnnotator.annotate(GraphQLValidationAnnotator.java:213)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:338)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:271)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:300)
	at com.intellij.lang.jsgraphql.v1.ide.editor.JSGraphQLQueryContextHighlightVisitor.analyze(JSGraphQLQueryContextHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:214)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**To Reproduce**

Load this schema file into an IDE Editor Window:

```graphql
# https://graphql.org/learn/schema/#arguments
type Starship {
  id: ID!
  name: String!
  length(unit: LengthUnit = METER): Float
  #                         ^ This throws the NullPointerException
}
enum LengthUnit {
  METER
  FOOT
}
```

Or this one (closer to the original scenario where I first experienced this bug):
 
```graphql
schema {
  query: Query
}
type Query {
  getThing: Thing
}
type Mutation {
  putThing(optionalArg: String): Thing
  listThings(includeInactive: Boolean = false): [Thing]
  #                                     ^ This throws the NullPointerException
}

type Thing {
  id: ID
  inactive: Boolean
}
```

**Expected behavior**
No null pointer exceptions :) 

I also would like to be able to use default values for Field Arguments (which is how I discovered this error). 

**Version and Environment Details**

**Plugin Version:** 2.6.0.

```
WebStorm 2020.2.3
Build #WS-202.7660.23, built on September 30, 2020
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 8083M
Cores: 16
Registry: debugger.valueTooltipAutoShowOnSelection=true, ide.balloon.shadow.size=0, js.debugger.webconsole=false
Non-Bundled Plugins: com.dubreuia, bundled-webstorm-help, com.jetbrains.plugins.ini4idea, com.mallowigi, dev.patrickpichler.darculaPitchBlackTheme, com.vladsch.idea.multimarkdown, com.intellij.database, aws.toolkit, com.intellij.lang.jsgraphql, io.plugin.tsnode
```

**Additional context**

I found this while working on a very large schema, but the examples given reproduce it 100% of the time for me. It pretty much happens any time a field has default arguments.

Example taken from https://graphql.org/learn/schema/#arguments 

> ### Arguments
> Every field on a GraphQL object type can have zero or more arguments, for example the length field below:

```graphql
type Starship {
  id: ID!
  name: String!
  length(unit: LengthUnit = METER): Float
}
```
> All arguments are named. Unlike languages like JavaScript and Python where functions take a list of ordered arguments, all arguments in GraphQL are passed by name specifically. In this case, the `length` field has one defined argument, `unit`.

> Arguments can be either required or optional. When an argument is optional, we can define a default value - if the `unit` argument is not passed, it will be set to `METER` by default.

**Comment by vepanimas** [comment]
Hi! Thank you for the report. I fixed this exception, but support for default parameters still isn't perfect, e.g. autocomplete and resolve in objects, enum values, and so on. I hope to work on it during the next several months.
