### ISSUE TITLE
Error: Cannot create class com.intellij.lang.jsgraphql.ide.notifications.GraphQLScopeEditorNotificationProvider

### ISSUE THREAD

**Issue by keegan-lillo** [jimkyndemeyer/js-graphql-intellij-plugin#470]
**Describe the bug**

Hi, 

I get the following error when launching WebStorm EAP WS-212.4321.17. However, everything seems to work fine otherwise.

```
com.intellij.diagnostic.PluginException: Cannot create class com.intellij.lang.jsgraphql.ide.notifications.GraphQLScopeEditorNotificationProvider (classloader=PluginClassLoader(plugin=PluginDescriptor(name=JS GraphQL, id=com.intellij.lang.jsgraphql, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/212.4321.17/WebStorm 2021.2 EAP.app.plugins/js-graphql-intellij-plugin, version=2.9.1, package=null), packagePrefix=null, instanceId=76, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:873)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.java:98)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:115)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:66)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:482)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:430)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.calcExtensionList(ExtensionPointImpl.java:244)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:238)
	at com.intellij.openapi.extensions.ProjectExtensionPointName.getExtensions(ProjectExtensionPointName.java:37)
	at com.intellij.openapi.project.DumbService.getDumbAwareExtensions(DumbService.java:83)
	at com.intellij.ui.EditorNotificationsImpl.calcNotificationUpdates(EditorNotificationsImpl.java:162)
	at com.intellij.ui.EditorNotificationsImpl.lambda$updateEditors$4(EditorNotificationsImpl.java:149)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(Project,EditorNotifications)GraphQLScopeEditorNotificationProvider to ()Object
	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:861)
	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:847)
	at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:495)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:853)
	... 39 more
```

WebStorm version info:

```
WebStorm 2021.2 EAP
Build #WS-212.4321.17, built on June 17, 2021
WebStorm EAP User
Expiration date: July 17, 2021
Runtime version: 11.0.11+9-b1504.3 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Registry: show.diff.preview.as.editor.tab.with.single.click=true, vcs.local.changes.toolbar.horizontal=false, documentation.show.toolbar=true, ide.balloon.shadow.size=0, ide.images.show.chessboard=true
Non-Bundled Plugins: com.intellij.lang.jsgraphql (2.9.1)
```

**To Reproduce**
Example repo: https://github.com/keegan-lillo/linters
1. Launch WebStorm EAP 
2. Open any project. (Doesn't even need to have any GraphQL) 

**Expected behavior**
No errors being reported.

**Screenshots**

**Version and Environment Details**
Operation system: [version]
IDE name and version: [version]
Plugin version: [version]

**Additional context**
I see no errors in the stable version:

```
WebStorm 2021.1.2
Build #WS-211.7442.26, built on May 25, 2021
Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: documentation.show.toolbar=true, vcs.commit.tool.window=false, vcs.local.changes.toolbar.horizontal=false, ide.images.show.chessboard=true
Non-Bundled Plugins: com.intellij.lang.jsgraphql (2.9.1)
```

**Comment by vepanimas** [comment]
@keegan-lillo hi, thank you for this report! It's fixed in the recent plugin update I'm preparing right now.

**Comment by kagof** [comment]
FYI this issue also appears in IntelliJ 2021.2, which has recently been released

**Comment by vepanimas** [comment]
Hi! It should be fixed in the new release https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/479#issuecomment-888327741
