### ISSUE TITLE
Incompatibility with 2021.2?

### ISSUE THREAD

**Issue by jrobens** [jimkyndemeyer/js-graphql-intellij-plugin#481]
Incompatible with  2021.2? 

```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Licensed to Interlated Pty Ltd / John Robens
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5
GC: ParNew, ConcurrentMarkSweep
Memory: 2493M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: com.jetbrains.plugins.ini4idea (212.4746.57), com.intellij.plugins.watcher (212.4746.52), org.jetbrains.plugins.localization (212.4746.57), org.logtalk (1.0.15), com.perl5 (2021.2), Pythonid (212.4746.96), org.jetbrains.plugins.ruby (212.4746.92), Karma (212.4746.57), org.jetbrains.plugins.vue (212.4746.57), aws.toolkit (1.29-212), com.intellij.lang.jsgraphql (2.9.1), com.jetbrains.php (212.4746.92), de.espend.idea.php.annotation (8.0.0), com.jetbrains.php.framework (212.4746.57), com.jetbrains.php.drupal (212.4746.52), com.jetbrains.twig (212.4746.57), fr.adrienbrault.idea.symfony2plugin (0.23.210), de.espend.idea.php.drupal (0.5.1)
Kotlin: 212-1.5.10-release-IJ4746.92]
```

Stack trace - can't convert object

`com.intellij.diagnostic.PluginException: Cannot create extension (class=com.intellij.lang.jsgraphql.ide.notifications.GraphQLScopeEditorNotificationProvider) [Plugin: com.intellij.lang.jsgraphql]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:932)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:88)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:486)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:434)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.calcExtensionList(ExtensionPointImpl.java:241)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:235)
	at com.intellij.openapi.extensions.ProjectExtensionPointName.getExtensions(ProjectExtensionPointName.java:37)
	at com.intellij.openapi.project.DumbService.getDumbAwareExtensions(DumbService.java:83)
	at com.intellij.ui.EditorNotificationsImpl.calcNotificationUpdates(EditorNotificationsImpl.java:162)
	at com.intellij.ui.EditorNotificationsImpl.lambda$updateEditors$4(EditorNotificationsImpl.java:149)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class com.intellij.lang.jsgraphql.ide.notifications.GraphQLScopeEditorNotificationProvider (classloader=PluginClassLoader(plugin=PluginDescriptor(name=JS GraphQL, id=com.intellij.lang.jsgraphql, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/js-graphql-intellij-plugin, version=2.9.1, package=null), packagePrefix=null, instanceId=227, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:870)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.java:99)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:116)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:66)
	... 36 more
Caused by: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(Project,EditorNotifications)GraphQLScopeEditorNotificationProvider to ()Object
	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:861)
	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:847)
	at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:495)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:854)
	... 39 more`

**Comment by vepanimas** [comment]
Hi! It should be [resolved](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/479#issuecomment-888346478) in 3.0.0, have you tried to update the plugin?

**Comment by jrobens** [comment]
Thank you. Works.
