### ISSUE TITLE
Cannot use plugin in Windows 10

### ISSUE THREAD

**Issue by david-benes** [jimkyndemeyer/js-graphql-intellij-plugin#68]
I'm unable to use this plugin in Windows 10.
For some reason, it looks for node binary in \usr\local\bin, which I don't have in Windows.
Is it possible to change this binary path? (I wasn't able to find any plugin configuration in Webstorm)

```Error running JS GraphQL Language Service using Node.js: Cannot run program "\usr\local\bin\node.exe" (in directory "C:\Users\user1\.WebStorm2016.3\config\plugins"): CreateProcess error=2, Systém nemůže nalézt uvedený soubor
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "\usr\local\bin\node.exe" (in directory "C:\Users\user1\.WebStorm2016.3\config\plugins"): CreateProcess error=2, Systém nemůže nalézt uvedený soubor
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:369)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceInstance.createProcessHandler(JSGraphQLNodeLanguageServiceInstance.java:135)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceInstance.<init>(JSGraphQLNodeLanguageServiceInstance.java:83)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.getJSGraphQLNodeLanguageServiceInstance(JSGraphQLNodeLanguageServiceClient.java:118)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.executeRequest(JSGraphQLNodeLanguageServiceClient.java:71)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.executeRequest(JSGraphQLNodeLanguageServiceClient.java:66)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.getTokens(JSGraphQLNodeLanguageServiceClient.java:33)
	at com.intellij.lang.jsgraphql.lexer.JSGraphQLLexer.fetchTokensFromLanguageService(JSGraphQLLexer.java:78)
	at com.intellij.lang.jsgraphql.lexer.JSGraphQLLexer.start(JSGraphQLLexer.java:66)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.a(LexerEditorHighlighter.java:336)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:317)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.loadEditorInBackground(TextEditorImpl.java:68)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:50)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader$1.a(AsyncEditorLoader.java:83)
	at com.intellij.psi.impl.PsiDocumentManagerBase$6.run(PsiDocumentManagerBase.java:477)
	at com.intellij.psi.impl.PsiDocumentManagerBase$7.compute(PsiDocumentManagerBase.java:506)
	at com.intellij.psi.impl.PsiDocumentManagerBase$7.compute(PsiDocumentManagerBase.java:502)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:899)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:502)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:474)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader$1.runBackgroundProcess(AsyncEditorLoader.java:77)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.a(AsyncEditorLoader.java:135)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:135)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.a(AsyncEditorLoader.java:135)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Cannot run program "\usr\local\bin\node.exe" (in directory "C:\Users\user1\.WebStorm2016.3\config\plugins"): CreateProcess error=2, Systém nemůže nalézt uvedený soubor
	at java.lang.ProcessBuilder.start(Unknown Source)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:379)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:365)
	... 36 more
Caused by: java.io.IOException: CreateProcess error=2, Systém nemůže nalézt uvedený soubor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 39 more```

**Comment by jimkyndemeyer** [comment]
Hi David. Please see https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/37 for a solution.

**Comment by jimkyndemeyer** [comment]
Hi David.

The plugin gets the node.js path directly from Webstorm/IntelliJ:

https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/master/src/main/com/intellij/lang/jsgraphql/languageservice/JSGraphQLNodeLanguageServiceInstance.java#L91-L93

I'm not aware of any alternatives to this code, so I recommend you try JetBrains support.

Best regards,
Jim.

**Comment by david-benes** [comment]
Thanks @jimkyndemeyer 

I just reported to JetBrains:
https://youtrack.jetbrains.com/issue/WEB-26030

**Comment by david-benes** [comment]
I found the issue, it was related to my (invalid) project config, not this plugin nor the IDEA.

More detailed explanation here:
https://youtrack.jetbrains.com/issue/WEB-26030
