### ISSUE TITLE
Not working in PHPStorm 2016.1

### ISSUE THREAD

**Issue by robrichard** [jimkyndemeyer/js-graphql-intellij-plugin#7]
Just updated PHPStorm to 2016.1 and I'm getting this error. I have also updated the NodeJS plugin to the latest version.

```
Error running JS GraphQL Language Service using Node.js: Executable is not specified
com.intellij.execution.ExecutionException: Executable is not specified
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:343)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:37)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceInstance.createProcessHandler(JSGraphQLNodeLanguageServiceInstance.java:134)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceInstance.<init>(JSGraphQLNodeLanguageServiceInstance.java:79)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.getJSGraphQLNodeLanguageServiceInstance(JSGraphQLNodeLanguageServiceClient.java:127)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.executeRequest(JSGraphQLNodeLanguageServiceClient.java:80)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.executeRequest(JSGraphQLNodeLanguageServiceClient.java:75)
	at com.intellij.lang.jsgraphql.languageservice.JSGraphQLNodeLanguageServiceClient.getTokens(JSGraphQLNodeLanguageServiceClient.java:33)
	at com.intellij.lang.jsgraphql.lexer.JSGraphQLLexer.fetchTokensFromLanguageService(JSGraphQLLexer.java:87)
	at com.intellij.lang.jsgraphql.lexer.JSGraphQLLexer.start(JSGraphQLLexer.java:75)
	at com.intellij.lexer.Lexer.start(Lexer.java:47)
	at com.intellij.lang.impl.PsiBuilderImpl.a(PsiBuilderImpl.java:268)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:194)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:202)
	at com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:52)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:83)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.b(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810)
	at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.a(MultiHostRegistrarImpl.java:356)
	at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.doneInjecting(MultiHostRegistrarImpl.java:236)
	at com.intellij.lang.jsgraphql.ide.injection.JSGraphQLTemplateFragmentLanguageInjector.getLanguagesToInject(JSGraphQLTemplateFragmentLanguageInjector.java:63)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:474)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:316)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:145)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:118)
	at com.intellij.lang.jsgraphql.ide.formatter.JSGraphQLBlockWrapper.buildChildren(JSGraphQLBlockWrapper.java:82)
	at com.intellij.psi.formatter.common.AbstractBlock.getSubBlocks(AbstractBlock.java:62)
	at com.intellij.lang.jsgraphql.ide.formatter.JSGraphQLBlockWrapper.getSubBlocks(JSGraphQLBlockWrapper.java:126)
	at com.intellij.psi.formatter.common.NewLineBlocksIterator.b(NewLineBlocksIterator.java:115)
	at com.intellij.psi.formatter.common.NewLineBlocksIterator.a(NewLineBlocksIterator.java:100)
	at com.intellij.psi.formatter.common.NewLineBlocksIterator.a(NewLineBlocksIterator.java:55)
	at com.intellij.psi.formatter.common.NewLineBlocksIterator.hasNext(NewLineBlocksIterator.java:48)
	at com.intellij.psi.codeStyle.autodetect.FormatterBasedLineIndentInfoBuilder.a(FormatterBasedLineIndentInfoBuilder.java:132)
	at com.intellij.psi.codeStyle.autodetect.FormatterBasedLineIndentInfoBuilder.build(FormatterBasedLineIndentInfoBuilder.java:49)
	at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.a(IndentOptionsDetectorImpl.java:80)
	at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.getIndentOptions(IndentOptionsDetectorImpl.java:59)
	at com.intellij.psi.codeStyle.autodetect.DetectableIndentOptionsProvider.getIndentOptions(DetectableIndentOptionsProvider.java:56)
	at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:672)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.updateDocumentIndentOptions(CodeStyleSettingsManager.java:145)
	at com.intellij.openapi.editor.impl.SettingsImpl.a(SettingsImpl.java:345)
	at com.intellij.openapi.editor.impl.SettingsImpl.reinitSettings(SettingsImpl.java:319)
	at com.intellij.openapi.editor.impl.EditorImpl.reinitSettings(EditorImpl.java:798)
	at com.intellij.openapi.editor.impl.EditorImpl.setHighlighter(EditorImpl.java:1204)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.b(TextEditorComponent.java:239)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.access$200(TextEditorComponent.java:63)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent$1.exitDumbMode(TextEditorComponent.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:359)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:345)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:336)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy73.beforePsiChanged(Unknown Source)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChange(PsiManagerImpl.java:494)
	at com.intellij.psi.impl.PsiManagerImpl.beforePropertyChange(PsiManagerImpl.java:287)
	at com.intellij.psi.impl.file.impl.FileManagerImpl$FileTypesChanged.run(FileManagerImpl.java:334)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.a(FileManagerImpl.java:347)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.b(FileManagerImpl.java:100)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.access$300(FileManagerImpl.java:54)
	at com.intellij.psi.impl.file.impl.FileManagerImpl$3.exitDumbMode(FileManagerImpl.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:359)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:345)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:336)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy56.daemonCancelEventOccurred(Unknown Source)
	at com.intellij.codeInsight.daemon.impl.DaemonListeners.a(DaemonListeners.java:607)
	at com.intellij.codeInsight.daemon.impl.DaemonListeners.access$600(DaemonListeners.java:95)
	at com.intellij.codeInsight.daemon.impl.DaemonListeners$7.exitDumbMode(DaemonListeners.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:359)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:345)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:336)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy51.modificationCountChanged(Unknown Source)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.incCounter(PsiModificationTrackerImpl.java:68)
	at com.intellij.psi.impl.PsiModificationTrackerImpl$1$1.run(PsiModificationTrackerImpl.java:47)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at com.intellij.psi.impl.PsiModificationTrackerImpl$1.a(PsiModificationTrackerImpl.java:44)
	at com.intellij.psi.impl.PsiModificationTrackerImpl$1.exitDumbMode(PsiModificationTrackerImpl.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:359)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:345)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:338)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy57.exitDumbMode(Unknown Source)
	at com.intellij.openapi.project.DumbServiceImpl.b(DumbServiceImpl.java:311)
	at com.intellij.openapi.project.DumbServiceImpl.access$1300(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$4.run(DumbServiceImpl.java:304)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:302)
	at com.intellij.openapi.project.DumbServiceImpl.access$1100(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$12.run(DumbServiceImpl.java:511)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by jimkyndemeyer** [comment]
Hi Rob.

I can't reproduce this problem locally. The plugin appears to work as expected with both IntelliJ IDEA 2016.1 and PHPStorm 2016.1.

Can you check your settings and verify that PHPStorm has found Node.js on your machine? See attached screenshot:

![phpstorm](https://cloud.githubusercontent.com/assets/15837712/14029510/cf589ed0-f202-11e5-8d3e-4c5cd8188651.png)

**Comment by robrichard** [comment]
Weird, I uninstalled the plugin and re-installed it and it's working now. Thanks for taking a look.
